<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administrators are not allowed to access API' => 'Администраторам запрещено получать доступ в АПИ',
    'Create User' => 'Добавить пользователя',
    'Data Validation Error' => 'Ошибка валидации данных',
    'Invalid Email or Password' => 'Неправильный E-mail или пароль',
    'Logout' => 'Выйти',
    'Password' => 'Пароль',
    'Repeat password' => 'Повторите пароль',
    'Save' => 'Сохранить',
    'Update' => 'Редактировать',
    'Users' => 'Пользователи',
    'Answer' => 'Ответ',
    'Api Loggers' => 'API-логгер',
    'ApiLogger' => 'API-логгер',
    'App Platform' => 'Платформа',
    'App Version' => 'Версия приложения',
    'Auth Key' => '',
    'Authorisation Error' => '',
    'Confirmation Token' => '',
    'Created At' => 'Дата создания',
    'Delete' => '',
    'Deleted At' => '',
    'Duration' => 'Длительность, сек',
    'Email' => '',
    'Email Confirmed' => '',
    'Headers' => 'Заголовки',
    'ID' => '',
    'Method' => 'Метод',
    'Password Hash' => '',
    'Request' => '',
    'Status' => '',
    'Superadmin' => '',
    'Updated At' => '',
    'Url' => '',
    'User ID' => 'Пользователь',
    'User not found' => '',
    'Username' => '',
    'Login' => '@@@@',
    'Remember me' => '@@@@',
];
